"""empty message

Revision ID: 42d85c765a37
Revises: d9fb47e1c90
Create Date: 2013-09-13 15:00:32.748755

"""

# revision identifiers, used by Alembic.
revision = '42d85c765a37'
down_revision = 'd9fb47e1c90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('status', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
